#!/bin/bash

MOUNT_PREFIX="/media/myarray"   # Set this to the directory where all your farm disks (HDD) are mounted
DISK_PREFIX="ChiaArray"         # All your disks should be called xxxx0 xxxx1 xxxx2 - this is the xxxx part
NUM_DRIVES=5                    # Set this to the number of HDD farm disks you have 

watch -n 60 "for i in $(seq 0 "$(( NUM_DRIVES - 1 ))" ) ; do cd '${MOUNT_PREFIX}/${DISK_PREFIX}$i' && find . -name '*.plot' -exec ls -l {} \; ; done | grep -v \" 108\" | grep -v \" 224\""
